"""
生成干净的高质量离线词库
每行一个真正的英文单词 + 正确中文翻译
"""
import csv
from pathlib import Path

OUTPUT = Path(__file__).parent / "data" / "top1000_offline.csv"

# 高质量词表：(单词, 词性, 中文翻译, 英文释义)
# 覆盖：基础高频 + 雅思/托福/GRE 核心
WORDS = [
    # === 基础高频词 ===
    ("the", "art", "这；那", "definite article"),
    ("be", "v", "是；存在", "to exist"),
    ("of", "prep", "的；属于", "belonging to"),
    ("and", "conj", "和；并且", "also, in addition"),
    ("to", "prep", "到；向", "toward"),
    ("in", "prep", "在…里", "inside"),
    ("that", "pron", "那个", "that thing"),
    ("have", "v", "有；拥有", "to possess"),
    ("it", "pron", "它", "that thing"),
    ("for", "prep", "为了；因为", "for the purpose of"),
    ("on", "prep", "在…上", "on top of"),
    ("with", "prep", "和；用", "accompanying"),
    ("do", "v", "做；干", "to perform"),
    ("say", "v", "说；讲", "to speak"),
    ("get", "v", "得到；获得", "to obtain"),
    ("make", "v", "制作；做", "to create"),
    ("go", "v", "去；走", "to move"),
    ("know", "v", "知道；认识", "to be aware of"),
    ("take", "v", "拿；取", "to grasp"),
    ("see", "v", "看见；明白", "to perceive with eyes"),
    ("come", "v", "来；到达", "to arrive"),
    ("think", "v", "想；认为", "to have an opinion"),
    ("look", "v", "看；显得", "to direct eyes"),
    ("want", "v", "想要；需要", "to desire"),
    ("give", "v", "给；提供", "to provide"),
    ("use", "v", "使用；利用", "to employ"),
    ("find", "v", "找到；发现", "to discover"),
    ("tell", "v", "告诉；讲述", "to inform"),
    ("ask", "v", "问；请求", "to inquire"),
    ("work", "v", "工作；运转", "to labor"),
    ("seem", "v", "似乎；好像", "to appear"),
    ("feel", "v", "感觉；觉得", "to perceive"),
    ("try", "v", "尝试；努力", "to attempt"),
    ("leave", "v", "离开；留下", "to depart"),
    ("call", "v", "打电话；称呼", "to telephone"),
    ("need", "v", "需要；必需", "to require"),
    ("become", "v", "变成；成为", "to come to be"),
    ("mean", "v", "意味着；打算", "to signify"),
    ("keep", "v", "保持；保留", "to retain"),
    ("let", "v", "让；允许", "to allow"),
    ("begin", "v", "开始", "to start"),
    ("show", "v", "显示；表明", "to display"),
    ("hear", "v", "听见；听说", "to perceive sound"),
    ("play", "v", "玩；演奏", "to engage in game"),
    ("run", "v", "跑；经营", "to move quickly"),
    ("move", "v", "移动；感动", "to change position"),
    ("live", "v", "生活；居住", "to reside"),
    ("believe", "v", "相信；认为", "to trust"),
    ("hold", "v", "握住；举行", "to grasp"),
    ("bring", "v", "带来；引起", "to carry to"),
    ("happen", "v", "发生；碰巧", "to occur"),
    ("write", "v", "写；写作", "to compose text"),
    ("sit", "v", "坐；位于", "to be seated"),
    ("stand", "v", "站；忍受", "to be upright"),
    ("lose", "v", "失去；输", "to misplace"),
    ("pay", "v", "支付；偿还", "to give money"),
    ("meet", "v", "遇见；满足", "to encounter"),
    ("include", "v", "包括；包含", "to contain"),
    ("continue", "v", "继续；延续", "to proceed"),
    ("set", "v", "设置；放置", "to place"),
    ("learn", "v", "学习；得知", "to acquire knowledge"),
    ("change", "v", "改变；更换", "to make different"),
    ("lead", "v", "领导；引导", "to guide"),
    ("understand", "v", "理解；懂", "to comprehend"),
    ("watch", "v", "观看；注视", "to observe"),
    ("follow", "v", "跟随；遵循", "to come after"),
    ("stop", "v", "停止；阻止", "to cease"),
    ("create", "v", "创造；创建", "to make new"),
    ("speak", "v", "说话；发言", "to talk"),
    ("read", "v", "阅读；朗读", "to interpret text"),
    ("allow", "v", "允许；准许", "to permit"),
    ("add", "v", "添加；增加", "to join"),
    ("spend", "v", "花费；度过", "to use money/time"),
    ("grow", "v", "生长；增长", "to increase"),
    ("open", "v", "打开；开放", "to unclose"),
    ("walk", "v", "走；散步", "to move on foot"),
    ("win", "v", "赢；获胜", "to be victorious"),
    ("offer", "v", "提供；提出", "to present"),
    ("remember", "v", "记得；记住", "to recall"),
    ("love", "v", "爱；喜欢", "to feel affection"),
    ("consider", "v", "考虑；认为", "to think about"),
    ("appear", "v", "出现；显得", "to come into view"),
    ("buy", "v", "买；购买", "to purchase"),
    ("wait", "v", "等待；等候", "to stay in expectation"),
    ("serve", "v", "服务；供应", "to provide service"),
    ("die", "v", "死；消亡", "to cease living"),
    ("send", "v", "发送；派遣", "to dispatch"),
    ("expect", "v", "期望；预期", "to anticipate"),
    ("build", "v", "建造；建立", "to construct"),
    ("stay", "v", "停留；保持", "to remain"),
    ("fall", "v", "落下；下降", "to drop"),
    ("cut", "v", "切；削减", "to slice"),
    ("reach", "v", "到达；达到", "to arrive at"),
    ("kill", "v", "杀死", "to cause death"),
    ("remain", "v", "保持；剩余", "to stay"),
    ("suggest", "v", "建议；暗示", "to propose"),
    ("raise", "v", "提高；举起", "to lift up"),
    ("pass", "v", "通过；传递", "to go by"),
    ("sell", "v", "卖；出售", "to exchange for money"),
    ("require", "v", "需要；要求", "to need"),
    ("report", "v", "报告；报道", "to give account"),
    ("decide", "v", "决定；断定", "to make a decision"),
    ("pull", "v", "拉；拖", "to draw toward"),
    ("return", "v", "返回；归还", "to come back"),
    ("explain", "v", "解释；说明", "to make clear"),
    ("hope", "v", "希望；期望", "to desire with expectation"),
    ("develop", "v", "发展；开发", "to grow or advance"),
    ("carry", "v", "携带；搬运", "to transport"),
    ("break", "v", "打破；折断", "to separate into pieces"),
    ("receive", "v", "收到；接受", "to get"),
    ("agree", "v", "同意；赞成", "to consent"),
    ("support", "v", "支持；支撑", "to uphold"),
    ("produce", "v", "生产；产生", "to create"),
    ("eat", "v", "吃", "to consume food"),
    ("cover", "v", "覆盖；包括", "to place over"),
    ("catch", "v", "抓住；赶上", "to seize"),
    ("draw", "v", "画；拉", "to sketch"),
    ("choose", "v", "选择；挑选", "to select"),
    ("cause", "v", "引起；导致", "to make happen"),
    ("point", "v", "指向；指出", "to indicate"),
    ("listen", "v", "听；倾听", "to hear attentively"),
    ("realize", "v", "意识到；实现", "to become aware"),
    ("place", "v", "放置；安置", "to put"),
    ("close", "v", "关闭；结束", "to shut"),
    ("describe", "v", "描述；形容", "to give an account"),
    ("drive", "v", "驾驶；驱动", "to operate a vehicle"),
    ("cross", "v", "穿过；交叉", "to go across"),
    ("sound", "v", "听起来；发声", "to make noise"),
    ("complete", "v", "完成；使完整", "to finish"),
    ("increase", "v", "增加；增长", "to make larger"),
    ("turn", "v", "转动；变成", "to rotate"),
    ("start", "v", "开始；启动", "to begin"),
    ("fill", "v", "填满；充满", "to make full"),
    ("improve", "v", "改善；提高", "to make better"),
    ("check", "v", "检查；核对", "to verify"),
    ("mention", "v", "提及；说起", "to refer to"),
    ("provide", "v", "提供；供给", "to supply"),
    ("wonder", "v", "想知道；疑惑", "to be curious"),
    ("share", "v", "分享；共享", "to divide among"),
    ("plan", "v", "计划；打算", "to arrange in advance"),
    ("contain", "v", "包含；容纳", "to hold within"),
    ("reduce", "v", "减少；降低", "to make smaller"),
    ("avoid", "v", "避免；回避", "to keep away from"),
    ("compare", "v", "比较；对比", "to examine differences"),
    ("manage", "v", "管理；设法", "to control"),
    ("protect", "v", "保护；防护", "to keep safe"),
    ("remove", "v", "移除；去掉", "to take away"),
    ("discover", "v", "发现；发觉", "to find out"),
    ("establish", "v", "建立；确立", "to set up"),
    ("argue", "v", "争论；主张", "to debate"),
    ("prevent", "v", "防止；预防", "to stop from happening"),
    ("exist", "v", "存在；生存", "to have being"),
    ("perform", "v", "执行；表演", "to carry out"),
    ("accept", "v", "接受；同意", "to receive willingly"),
    ("achieve", "v", "实现；取得", "to accomplish"),
    ("claim", "v", "声称；索取", "to assert"),
    ("assume", "v", "假定；承担", "to suppose"),
    ("apply", "v", "申请；应用", "to put to use"),
    ("attack", "v", "攻击；抨击", "to assault"),
    ("attempt", "v", "尝试；企图", "to try"),
    ("attend", "v", "参加；出席", "to be present"),
    ("behave", "v", "表现；举止", "to act"),
    ("belong", "v", "属于", "to be owned by"),
    ("blame", "v", "责备；归咎", "to hold responsible"),
    ("borrow", "v", "借入", "to take temporarily"),
    ("bother", "v", "打扰；烦扰", "to annoy"),
    ("celebrate", "v", "庆祝", "to observe a special day"),
    ("challenge", "v", "挑战；质疑", "to dispute"),
    ("collect", "v", "收集；采集", "to gather"),
    ("communicate", "v", "交流；沟通", "to exchange information"),
    ("compete", "v", "竞争；比赛", "to contend"),
    ("complain", "v", "抱怨；投诉", "to express dissatisfaction"),
    ("concentrate", "v", "集中；专注", "to focus attention"),
    ("confirm", "v", "确认；证实", "to verify"),
    ("connect", "v", "连接；联系", "to join together"),
    ("consist", "v", "组成；在于", "to be composed of"),
    ("contact", "v", "联系；接触", "to communicate with"),
    ("contribute", "v", "贡献；捐助", "to give"),
    ("control", "v", "控制；管理", "to direct"),
    ("convince", "v", "说服；使相信", "to persuade"),
    ("count", "v", "数；计数", "to enumerate"),
    ("delay", "v", "推迟；延误", "to postpone"),
    ("deliver", "v", "递送；发表", "to carry to destination"),
    ("demand", "v", "要求；需要", "to ask forcefully"),
    ("depend", "v", "依赖；取决于", "to rely on"),
    ("design", "v", "设计；构思", "to create a plan"),
    ("destroy", "v", "破坏；毁灭", "to ruin"),
    ("determine", "v", "决定；确定", "to decide"),
    ("distinguish", "v", "区分；辨别", "to tell apart"),
    ("distribute", "v", "分配；分发", "to give out"),
    ("earn", "v", "赚取；获得", "to gain by work"),
    ("educate", "v", "教育；培养", "to teach"),
    ("eliminate", "v", "消除；淘汰", "to remove"),
    ("emphasize", "v", "强调；着重", "to stress"),
    ("encourage", "v", "鼓励；激励", "to give courage"),
    ("engage", "v", "参与；从事", "to involve"),
    ("enjoy", "v", "享受；喜欢", "to take pleasure in"),
    ("escape", "v", "逃跑；逃避", "to get away"),
    ("estimate", "v", "估计；估算", "to approximate"),
    ("evaluate", "v", "评估；评价", "to assess"),
    ("examine", "v", "检查；审查", "to inspect closely"),
    ("exchange", "v", "交换；交流", "to trade"),
    ("exercise", "v", "锻炼；行使", "to train body"),
    ("expand", "v", "扩大；扩展", "to enlarge"),
    ("express", "v", "表达；表示", "to convey"),
    ("extend", "v", "延伸；扩展", "to stretch out"),
    ("fail", "v", "失败；不及格", "to not succeed"),
    ("fear", "v", "害怕；恐惧", "to be afraid"),
    ("focus", "v", "聚焦；集中", "to concentrate"),
    ("forget", "v", "忘记", "to fail to remember"),
    ("gain", "v", "获得；增加", "to obtain"),
    ("gather", "v", "收集；聚集", "to bring together"),
    ("generate", "v", "产生；生成", "to produce"),
    ("guarantee", "v", "保证；担保", "to promise"),
    ("handle", "v", "处理；应付", "to manage"),
    ("hide", "v", "隐藏；躲藏", "to conceal"),
    ("identify", "v", "识别；确认", "to recognize"),
    ("ignore", "v", "忽视；不理", "to disregard"),
    ("imagine", "v", "想象；设想", "to form mental image"),
    ("imply", "v", "暗示；意味着", "to suggest"),
    ("impress", "v", "给…深刻印象", "to affect deeply"),
    ("indicate", "v", "表明；指示", "to point out"),
    ("influence", "v", "影响", "to affect"),
    ("insist", "v", "坚持；坚决要求", "to demand firmly"),
    ("inspect", "v", "检查；视察", "to examine carefully"),
    ("install", "v", "安装；设置", "to set up"),
    ("intend", "v", "打算；意图", "to plan"),
    ("introduce", "v", "介绍；引入", "to present"),
    ("invest", "v", "投资；投入", "to put money in"),
    ("involve", "v", "涉及；包含", "to include"),
    ("judge", "v", "判断；评判", "to form opinion"),
    ("maintain", "v", "维持；保养", "to keep up"),
    ("measure", "v", "测量；衡量", "to determine size"),
    ("obtain", "v", "获得；得到", "to acquire"),
    ("occur", "v", "发生；出现", "to happen"),
    ("operate", "v", "操作；运转", "to function"),
    ("organize", "v", "组织；安排", "to arrange"),
    ("overcome", "v", "克服；战胜", "to defeat"),
    ("participate", "v", "参与；参加", "to take part"),
    ("perceive", "v", "感知；察觉", "to become aware"),
    ("persuade", "v", "说服；劝说", "to convince"),
    ("possess", "v", "拥有；具备", "to own"),
    ("predict", "v", "预测；预言", "to foretell"),
    ("prepare", "v", "准备；预备", "to make ready"),
    ("present", "v", "呈现；赠送", "to give"),
    ("pretend", "v", "假装；装作", "to feign"),
    ("process", "v", "处理；加工", "to handle"),
    ("promise", "v", "承诺；许诺", "to pledge"),
    ("propose", "v", "提议；建议", "to suggest"),
    ("prove", "v", "证明；证实", "to demonstrate"),
    ("publish", "v", "出版；发表", "to make public"),
    ("purchase", "v", "购买", "to buy"),
    ("pursue", "v", "追求；追赶", "to follow"),
    ("recognize", "v", "认出；承认", "to identify"),
    ("recommend", "v", "推荐；建议", "to suggest favorably"),
    ("recover", "v", "恢复；康复", "to get back"),
    ("reduce", "v", "减少；降低", "to make smaller"),
    ("refer", "v", "提到；参考", "to mention"),
    ("reflect", "v", "反射；反映", "to mirror"),
    ("refuse", "v", "拒绝", "to decline"),
    ("regard", "v", "认为；看待", "to consider"),
    ("reject", "v", "拒绝；驳回", "to refuse"),
    ("relate", "v", "联系；讲述", "to connect"),
    ("release", "v", "释放；发布", "to set free"),
    ("rely", "v", "依赖；信赖", "to depend"),
    ("represent", "v", "代表；象征", "to stand for"),
    ("request", "v", "请求；要求", "to ask for"),
    ("respond", "v", "回应；回答", "to reply"),
    ("reveal", "v", "揭示；透露", "to disclose"),
    ("satisfy", "v", "满足；使满意", "to fulfill"),
    ("seek", "v", "寻求；寻找", "to search for"),
    ("select", "v", "选择；挑选", "to choose"),
    ("solve", "v", "解决；解答", "to find solution"),
    ("struggle", "v", "挣扎；奋斗", "to strive"),
    ("submit", "v", "提交；呈递", "to present for review"),
    ("succeed", "v", "成功；继承", "to accomplish"),
    ("supply", "v", "供应；提供", "to provide"),
    ("survive", "v", "幸存；存活", "to remain alive"),
    ("tend", "v", "倾向；照料", "to incline"),
    ("threaten", "v", "威胁；恐吓", "to menace"),
    ("transfer", "v", "转移；转让", "to move"),
    ("transform", "v", "转变；改造", "to change form"),
    ("treat", "v", "对待；治疗", "to deal with"),
    ("vary", "v", "变化；不同", "to differ"),
    ("warn", "v", "警告；提醒", "to caution"),
    ("waste", "v", "浪费", "to use carelessly"),
    ("wish", "v", "希望；祝愿", "to desire"),

    # === 雅思/托福/GRE 核心词 ===
    ("abandon", "v", "放弃；抛弃", "to give up completely"),
    ("abolish", "v", "废除；取消", "to officially end"),
    ("abstract", "adj", "抽象的", "existing as an idea"),
    ("abundant", "adj", "丰富的；充裕的", "plentiful"),
    ("accelerate", "v", "加速；促进", "to speed up"),
    ("accommodate", "v", "容纳；适应", "to provide space"),
    ("accumulate", "v", "积累；积聚", "to gather over time"),
    ("accurate", "adj", "准确的；精确的", "exact, correct"),
    ("acknowledge", "v", "承认；致谢", "to admit"),
    ("acquire", "v", "获得；习得", "to gain"),
    ("adapt", "v", "适应；改编", "to adjust"),
    ("adequate", "adj", "足够的；适当的", "sufficient"),
    ("adjacent", "adj", "邻近的；毗邻的", "next to"),
    ("advocate", "v", "提倡；主张", "to support"),
    ("aesthetic", "adj", "美学的；审美的", "relating to beauty"),
    ("aggressive", "adj", "侵略性的；好斗的", "forceful"),
    ("allocate", "v", "分配；拨给", "to assign"),
    ("alternative", "n", "替代方案", "another option"),
    ("ambiguous", "adj", "模棱两可的", "unclear"),
    ("analyze", "v", "分析；解析", "to examine in detail"),
    ("anticipate", "v", "预期；预料", "to expect"),
    ("apparent", "adj", "显然的；表面的", "obvious"),
    ("appreciate", "v", "欣赏；感激", "to value"),
    ("appropriate", "adj", "适当的；恰当的", "suitable"),
    ("arbitrary", "adj", "任意的；武断的", "random"),
    ("artificial", "adj", "人工的；人造的", "man-made"),
    ("assess", "v", "评估；评定", "to evaluate"),
    ("assign", "v", "分配；指派", "to allocate"),
    ("associate", "v", "联想；联系", "to connect"),
    ("assume", "v", "假设；承担", "to suppose"),
    ("attain", "v", "达到；获得", "to achieve"),
    ("attribute", "v", "归因于", "to credit to"),
    ("authentic", "adj", "真实的；可靠的", "genuine"),
    ("aware", "adj", "意识到的；知道的", "conscious of"),
    ("bias", "n", "偏见；偏向", "prejudice"),
    ("capacity", "n", "能力；容量", "ability, volume"),
    ("category", "n", "类别；范畴", "class, group"),
    ("cease", "v", "停止；终止", "to stop"),
    ("clarify", "v", "澄清；阐明", "to make clear"),
    ("coherent", "adj", "连贯的；一致的", "logical"),
    ("coincide", "v", "巧合；一致", "to happen together"),
    ("collapse", "v", "倒塌；崩溃", "to fall down"),
    ("commence", "v", "开始", "to begin"),
    ("commodity", "n", "商品；货物", "goods"),
    ("compensate", "v", "补偿；赔偿", "to make up for"),
    ("competent", "adj", "有能力的；胜任的", "capable"),
    ("complement", "v", "补充；补足", "to complete"),
    ("complex", "adj", "复杂的", "complicated"),
    ("comprehensive", "adj", "全面的；综合的", "complete, thorough"),
    ("comprise", "v", "包含；构成", "to consist of"),
    ("compromise", "n", "妥协；折中", "settlement"),
    ("concept", "n", "概念；观念", "idea"),
    ("conclude", "v", "得出结论；结束", "to end, to decide"),
    ("concrete", "adj", "具体的；实在的", "real, specific"),
    ("conduct", "v", "进行；引导", "to carry out"),
    ("confer", "v", "授予；商讨", "to grant, to discuss"),
    ("confine", "v", "限制；禁闭", "to restrict"),
    ("conform", "v", "符合；遵守", "to comply"),
    ("confront", "v", "面对；对抗", "to face"),
    ("consecutive", "adj", "连续的", "in a row"),
    ("consensus", "n", "共识；一致", "general agreement"),
    ("consequence", "n", "后果；结果", "result"),
    ("conserve", "v", "保护；节约", "to preserve"),
    ("consistent", "adj", "一致的；始终如一的", "steady, uniform"),
    ("constitute", "v", "构成；组成", "to form"),
    ("constrain", "v", "限制；约束", "to restrict"),
    ("construct", "v", "建造；构建", "to build"),
    ("consult", "v", "咨询；查阅", "to seek advice"),
    ("consume", "v", "消耗；消费", "to use up"),
    ("contemplate", "v", "沉思；考虑", "to think deeply"),
    ("contemporary", "adj", "当代的；同时代的", "modern"),
    ("contradict", "v", "反驳；矛盾", "to oppose"),
    ("controversial", "adj", "有争议的", "debatable"),
    ("conventional", "adj", "传统的；常规的", "traditional"),
    ("convey", "v", "传达；运送", "to communicate"),
    ("crucial", "adj", "关键的；重要的", "critical"),
    ("cultivate", "v", "培养；耕作", "to nurture"),
    ("decline", "v", "下降；婉拒", "to decrease, to refuse"),
    ("deduce", "v", "推断；演绎", "to infer"),
    ("deficiency", "n", "缺乏；不足", "shortage"),
    ("demonstrate", "v", "证明；展示", "to show clearly"),
    ("derive", "v", "源自；获得", "to obtain from"),
    ("deteriorate", "v", "恶化；退化", "to worsen"),
    ("deviate", "v", "偏离；背离", "to depart from"),
    ("dimension", "n", "维度；尺寸", "aspect, size"),
    ("diminish", "v", "减少；缩小", "to decrease"),
    ("discriminate", "v", "歧视；区别", "to distinguish"),
    ("displace", "v", "取代；转移", "to move, to replace"),
    ("dispose", "v", "处理；处置", "to get rid of"),
    ("distinct", "adj", "明显的；不同的", "clearly different"),
    ("distort", "v", "扭曲；歪曲", "to twist out of shape"),
    ("diverse", "adj", "多样的；不同的", "varied"),
    ("dominate", "v", "支配；主导", "to control"),
    ("dramatic", "adj", "戏剧性的；剧烈的", "striking"),
    ("dynamic", "adj", "动态的；有活力的", "energetic"),
    ("elaborate", "adj", "详尽的；复杂的", "detailed"),
    ("eliminate", "v", "消除；排除", "to remove"),
    ("emerge", "v", "出现；浮现", "to come forth"),
    ("empirical", "adj", "经验的；实证的", "based on observation"),
    ("enhance", "v", "提高；增强", "to improve"),
    ("enormous", "adj", "巨大的", "huge"),
    ("ensure", "v", "确保；保证", "to make certain"),
    ("equivalent", "adj", "相等的；等价的", "equal"),
    ("evolve", "v", "进化；演变", "to develop gradually"),
    ("exceed", "v", "超过；超越", "to surpass"),
    ("explicit", "adj", "明确的；清楚的", "clear, direct"),
    ("exploit", "v", "利用；剥削", "to use for benefit"),
    ("external", "adj", "外部的；外在的", "outside"),
    ("facilitate", "v", "促进；使便利", "to make easier"),
    ("fluctuate", "v", "波动；起伏", "to vary irregularly"),
    ("fundamental", "adj", "基本的；根本的", "basic"),
    ("generate", "v", "产生；生成", "to produce"),
    ("genuine", "adj", "真实的；真诚的", "authentic"),
    ("hypothesis", "n", "假设；假说", "proposed explanation"),
    ("identify", "v", "识别；确认", "to recognize"),
    ("implicit", "adj", "含蓄的；隐含的", "implied"),
    ("incentive", "n", "激励；诱因", "motivation"),
    ("inevitable", "adj", "不可避免的", "unavoidable"),
    ("infer", "v", "推断；推论", "to deduce"),
    ("infrastructure", "n", "基础设施", "basic facilities"),
    ("inherent", "adj", "固有的；内在的", "intrinsic"),
    ("innovation", "n", "创新；革新", "new idea"),
    ("integrate", "v", "整合；融合", "to combine"),
    ("interpret", "v", "解释；诠释", "to explain"),
    ("intervene", "v", "干预；介入", "to interfere"),
    ("intrinsic", "adj", "固有的；本质的", "essential"),
    ("justify", "v", "证明…正当", "to show to be right"),
    ("legitimate", "adj", "合法的；正当的", "lawful"),
    ("levy", "v", "征收；征税", "to impose tax"),
    ("liberal", "adj", "开明的；自由的", "open-minded"),
    ("logic", "n", "逻辑；推理", "reasoning"),
    ("manifest", "adj", "明显的", "clear, obvious"),
    ("manipulate", "v", "操纵；操作", "to control"),
    ("marginal", "adj", "边缘的；微小的", "minor"),
    ("maximize", "v", "最大化", "to make as large as possible"),
    ("mechanism", "n", "机制；机理", "process"),
    ("mediate", "v", "调解；斡旋", "to settle dispute"),
    ("minimize", "v", "最小化；降低", "to reduce to minimum"),
    ("modify", "v", "修改；调整", "to change slightly"),
    ("monitor", "v", "监控；监测", "to observe"),
    ("mutual", "adj", "相互的；共同的", "shared"),
    ("neglect", "v", "忽视；疏忽", "to fail to care for"),
    ("neutral", "adj", "中立的", "impartial"),
    ("notion", "n", "概念；观念", "idea"),
    ("objective", "adj", "客观的", "unbiased"),
    ("obstacle", "n", "障碍；阻碍", "barrier"),
    ("offset", "v", "抵消；补偿", "to counterbalance"),
    ("ongoing", "adj", "持续的；进行中的", "continuing"),
    ("optimal", "adj", "最佳的；最优的", "best possible"),
    ("orient", "v", "使适应；定向", "to adjust, to direct"),
    ("paradigm", "n", "范式；典范", "model, pattern"),
    ("parameter", "n", "参数；界限", "factor, limit"),
    ("perceive", "v", "感知；理解", "to become aware"),
    ("persist", "v", "坚持；持续", "to continue firmly"),
    ("phenomenon", "n", "现象", "observable event"),
    ("potential", "adj", "潜在的；可能的", "possible"),
    ("precede", "v", "先于；领先", "to come before"),
    ("precise", "adj", "精确的；准确的", "exact"),
    ("predominant", "adj", "主要的；占主导的", "main, dominant"),
    ("preliminary", "adj", "初步的；预备的", "initial"),
    ("presume", "v", "假定；推测", "to suppose"),
    ("prevail", "v", "盛行；获胜", "to win, to be common"),
    ("principal", "adj", "主要的；首要的", "main"),
    ("principle", "n", "原则；原理", "rule, truth"),
    ("priority", "n", "优先；重点", "precedence"),
    ("profound", "adj", "深刻的；深远的", "deep, intense"),
    ("prohibit", "v", "禁止", "to forbid"),
    ("prominent", "adj", "突出的；著名的", "famous, noticeable"),
    ("promote", "v", "促进；晋升", "to advance"),
    ("prospect", "n", "前景；可能性", "possibility"),
    ("radical", "adj", "根本的；激进的", "extreme"),
    ("random", "adj", "随机的；任意的", "by chance"),
    ("rational", "adj", "理性的；合理的", "reasonable"),
    ("recover", "v", "恢复；康复", "to get back"),
    ("regulate", "v", "调节；管理", "to control"),
    ("reinforce", "v", "加强；强化", "to strengthen"),
    ("relevant", "adj", "相关的；切题的", "pertinent"),
    ("reluctant", "adj", "不情愿的；勉强的", "unwilling"),
    ("require", "v", "需要；要求", "to need"),
    ("resolve", "v", "解决；决心", "to settle"),
    ("restore", "v", "恢复；修复", "to bring back"),
    ("restrict", "v", "限制；约束", "to limit"),
    ("retain", "v", "保留；保持", "to keep"),
    ("reveal", "v", "揭示；透露", "to disclose"),
    ("reverse", "v", "颠倒；反转", "to turn around"),
    ("rigid", "adj", "僵硬的；严格的", "stiff, strict"),
    ("scenario", "n", "场景；方案", "situation"),
    ("scheme", "n", "计划；方案", "plan"),
    ("scope", "n", "范围；余地", "range"),
    ("sector", "n", "部门；领域", "section"),
    ("significant", "adj", "重要的；显著的", "important"),
    ("simulate", "v", "模拟；仿真", "to imitate"),
    ("sole", "adj", "唯一的；单独的", "only"),
    ("specify", "v", "明确说明；指定", "to state precisely"),
    ("sphere", "n", "领域；范围", "field, domain"),
    ("spontaneous", "adj", "自发的；自然的", "unplanned"),
    ("stable", "adj", "稳定的；牢固的", "steady"),
    ("stimulate", "v", "刺激；激励", "to encourage"),
    ("strategy", "n", "策略；战略", "plan"),
    ("subsequent", "adj", "随后的；后来的", "following"),
    ("substitute", "v", "替代；替换", "to replace"),
    ("sufficient", "adj", "足够的；充分的", "enough"),
    ("superior", "adj", "优越的；上级的", "better, higher"),
    ("sustain", "v", "维持；支撑", "to support"),
    ("temporary", "adj", "临时的；暂时的", "not permanent"),
    ("transform", "v", "转变；改造", "to change"),
    ("trigger", "v", "触发；引发", "to cause"),
    ("ultimate", "adj", "最终的；根本的", "final"),
    ("undergo", "v", "经历；经受", "to experience"),
    ("undermine", "v", "削弱；破坏", "to weaken"),
    ("unique", "adj", "独特的；唯一的", "one of a kind"),
    ("utilize", "v", "利用；使用", "to use"),
    ("valid", "adj", "有效的；合理的", "sound"),
    ("vary", "v", "变化；不同", "to differ"),
    ("viable", "adj", "可行的；能存活的", "workable"),
    ("virtual", "adj", "虚拟的；实际上的", "simulated"),
    ("visible", "adj", "可见的；明显的", "able to be seen"),
    ("widespread", "adj", "广泛的；普遍的", "extensive"),
]

print(f"词条总数: {len(WORDS)}")

# 去重（保留顺序）
seen = set()
unique = []
for w in WORDS:
    if w[0] not in seen:
        seen.add(w[0])
        unique.append(w)

print(f"去重后: {len(unique)}")

# 写 CSV
with OUTPUT.open('w', encoding='utf-8', newline='') as f:
    writer = csv.writer(f)
    writer.writerow(['word', 'phonetic', 'pos', 'translation', 'definition', 'collocation', 'frq'])
    for i, (word, pos, translation, definition) in enumerate(unique):
        ipa = ''
        frq = max(5, 95 - i // 3)  # 频率递减
        writer.writerow([word, ipa, pos, translation, definition, '', frq])

print(f"已保存 {len(unique)} 个高质量词到 {OUTPUT}")